"""Initial migration

Revision ID: d12a2ecdd039
Revises: 
Create Date: 2025-01-20 20:40:32.331527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'd12a2ecdd039'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    inspector = inspect(op.get_bind())
    if not inspector.has_table('baseline'):
        op.create_table('baseline',
            sa.Column('ticker', sa.String(), nullable=False),
            sa.Column('daily_performance', sqlite.JSON(), nullable=True),
            sa.Column('start_date', sa.Date(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('ticker')
        )
    
    if not inspector.has_table('thesis'):
        op.create_table('thesis',
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('author', sa.String(), nullable=False),
            sa.Column('ticker', sa.String(), nullable=False),
            sa.Column('company_name', sa.String(), nullable=True),
            sa.Column('link', sa.String(), nullable=True),
            sa.Column('market_cap', sa.Float(), nullable=True),
            sa.Column('price', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('text', sa.Text(), nullable=True),
            sa.Column('profile', sa.Text(), nullable=True),
            sa.Column('monthly_performance', sqlite.JSON(), nullable=True),
            sa.Column('dividends', sqlite.JSON(), nullable=True),
            sa.PrimaryKeyConstraint('date', 'author', 'ticker')
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis')
    op.drop_table('baseline')
    # ### end Alembic commands ###